name: check-cran-status

on:
  push:
    branches: [main, master]
  schedule:
    - cron: '0 6 * * 1,4' # Runs at 06:00 on Monday and Thursday, check https://crontab.guru/
jobs:
  check:
    runs-on: ubuntu-latest
    permissions: write-all # This line is important for creating issues, should be on jobs or global
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check
        uses: dieghernan/cran-status-check@v2
